### PR TITLE
Fix Issues With The Issue Templates --skip

### PR DESCRIPTION
**Pull request by ItzPancakse**

### CODE REVIEW

**Comment by Dueris** [comment]
Looks good. Thx for updating the issue template and fixing some things, I appreciate it.

**Comment by ItzPancakse** [comment]
should have [ci skip]

**Review by Dueris — APPROVED** [review]

**Comment by Dueris** [comment]
Do --skip at the end instead of ci skip

**Comment by ItzPancakse** [comment]
> Do --skip at the end instead of ci skip

oh ok i always put [ci skip] lol

**Pull request merged**
