### PR TITLE
Feat: Fix Chat Signing

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Dueris** [comment]
I'm confused. Whats broken?

**Comment by ghost** [comment]
You get kicked out cause of chat signing

**Comment by Dueris** [comment]
What?

**Comment by ghost** [comment]
like this 
image

**Comment by ghost** [comment]
very bad image but says stuff related to chat signature

**Comment by Dueris** [comment]
That's due to a weird error that happens when the client breaks itself. If it's not verified it will still break things. Just rejoin the server to fix it.

**Comment by ghost** [comment]
ik but its annoying to rejoin

**Comment by Dueris** [comment]
Would it be more annoying to have every chat message possibly break or to spend 5 seconds to rejoin

**Comment by ghost** [comment]
well if it breaks that cause issues so ig rejoin

**Comment by Dueris** [comment]
Then is there a need for this patch if it's just going to further break things and cause more of a hassle?

**Comment by ghost** [comment]
no

**Pull request closed without merging**
