### PR TITLE
Update: Minor Optimizations

### PR DESCRIPTION
**Pull request by ghost**
Added: Reduce Sensor Work

### CODE REVIEW

**Comment by Dueris** [comment]
Looks good

**Comment by ghost** [comment]
ty

**Comment by ghost** [comment]
https://github.com/Pancaksee/Pancakse-Canvas/actions/runs/7081777343/job/19271540330 heres the action i did

**Comment by Dueris** [comment]
Alright, looks good. Ty for the contribution

**Comment by ghost** [comment]
Np

**Pull request merged**
